### ISSUE TITLE
Replace Hard-coded Paths with Already Existing Variable

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/github-actions-for-desktop-apps#17] opened 2020-03-10 19:29 UTC
## Problematic

At the end of the YAML for the continuous integration example, the **upload-artifact** step `path` uses a hard coded folder path:

https://github.com/microsoft/github-actions-for-desktop-apps/blob/d0fbf5cbc39057dea30244fb7ef6c5ae9c3b1ab8/.github/workflows/ci.yml#L93

## Recommended

I believe this should be using the `Wap_Project_Directory` variable plus "AppPackages" subfolder instead.

Snippet

```yml
# Upload the MSIX package: https://github.com/marketplace/actions/upload-artifact
- name: Upload build artifacts
  uses: actions/upload-artifact@v1
  with:
    name: MSIX Package
    path: '$env:Wap_Project_Directory\AppPackages\'
```

[Edit] - Added the subfolder name to the variable. I'm not sure that's how to concatenate the variable with a string in GitHub actions yet, but you get the point

**Comment by edwardskrod** [comment] 2020-03-12 12:46
I remember investigating this when I was creating the workflows.   The problem is that we can't add an environment variable to a jobs.<job_id>.steps.with statement. 

The answer is to use steps to define a variable for the path.  I'll try it now.

**Comment by LanceMcCarthy** [comment] 2020-03-12 20:28
Since you already need the matrix variable for channel name, it wouldn't be too much fluff to add another variable. However, the who point of a variable is that it's value is different, so it defeats the purpose to have the same value in each matrix.

So instead, you could just add a comment where things are hard-coded. For example:
```
 # We need to use full path here because job variable is not in scope
 path: MyWpfApp.Package\AppPackages\ 
```
That way, developers who might clone/copy from this repo wont get hung up on a path that doesn't exist in their app (you know folks are going to copy/paste without drilling deeper into each value).

**Comment by lindexi** [comment] 2020-03-13 01:20
![图片](https://user-images.githubusercontent.com/16054566/76580692-d0c77680-650b-11ea-9772-a065feafe50a.png)

**Comment by lindexi** [comment] 2020-03-13 01:22
@LanceMcCarthy I think you are right, see https://github.com/dotnet-campus/TranslationTool/runs/504675788

**Comment by edwardskrod** [comment] 2020-04-02 17:32
Closed by https://github.com/microsoft/github-actions-for-desktop-apps/pull/26

**Closed** 2020-04-02 17:31 UTC
